name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3.5.2
      - name: Sync and merge upstream repository with your current repository
      # You may pin to the exact commit or the version.
      # uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/ARMkiyas/tess.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: main
          # Branch to merge into downstream
          downstream_branch: main
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}

 
